Handle missing profile gracefully
When user is created, the created user might not have a profile.  This
will generate an error in {{ $profile->title }} as follows.

  Error: Trying to get property 'title' on null

We need to use null-safe access in Blade through '?->' null-safe and
'??' fallback-if-null operators to prevent crashes and improve UX.